<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Laporan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Laporan_model');
    } 

    /*
     * Listing of laporan
     */
    function index()
    {
        $data['laporan'] = $this->Laporan_model->get_all_laporan();
        
        $data['_view'] = 'laporan/index';
        $this->load->view('laporan',$data);
    }

    /*
     * Adding a new laporan
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama_pelapor','Nama Pelapor','required');
		$this->form_validation->set_rules('no_ktp','No Ktp','required');
		$this->form_validation->set_rules('alamat','Alamat','required');
		$this->form_validation->set_rules('foto_ktp','Foto Ktp','required');
		$this->form_validation->set_rules('infrastruktur','Infrastruktur','required');
		$this->form_validation->set_rules('lokasi_namajalan','Lokasi Namajalan','required');
		$this->form_validation->set_rules('pengaduan','Pengaduan','required');
		$this->form_validation->set_rules('dokumentasi','Dokumentasi','required');
		$this->form_validation->set_rules('lokasi_koordinat','Lokasi Koordinat','required');
		$this->form_validation->set_rules('lokasi_distrik','Lokasi Distrik','required');
		$this->form_validation->set_rules('lokasi_kabkota','Lokasi Kabkota','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'infrastruktur' => $this->input->post('infrastruktur'),
				'tgl_laporan' => $this->input->post('tgl_laporan'),
				'nama_pelapor' => $this->input->post('nama_pelapor'),
				'no_ktp' => $this->input->post('no_ktp'),
				'foto_ktp' => $this->input->post('foto_ktp'),
				'lokasi_namajalan' => $this->input->post('lokasi_namajalan'),
				'lokasi_kabkota' => $this->input->post('lokasi_kabkota'),
				'lokasi_distrik' => $this->input->post('lokasi_distrik'),
				'lokasi_koordinat' => $this->input->post('lokasi_koordinat'),
				'dokumentasi' => $this->input->post('dokumentasi'),
				'alamat' => $this->input->post('alamat'),
				'pengaduan' => $this->input->post('pengaduan'),
            );
            
            $laporan_id = $this->Laporan_model->add_laporan($params);
            redirect('laporan/index');
        }
        else
        {            
            $data['_view'] = 'laporan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a laporan
     */
    function edit($id)
    {   
        // check if the laporan exists before trying to edit it
        $data['laporan'] = $this->Laporan_model->get_laporan($id);
        
        if(isset($data['laporan']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama_pelapor','Nama Pelapor','required');
			$this->form_validation->set_rules('no_ktp','No Ktp','required');
			$this->form_validation->set_rules('alamat','Alamat','required');
			$this->form_validation->set_rules('foto_ktp','Foto Ktp','required');
			$this->form_validation->set_rules('infrastruktur','Infrastruktur','required');
			$this->form_validation->set_rules('lokasi_namajalan','Lokasi Namajalan','required');
			$this->form_validation->set_rules('pengaduan','Pengaduan','required');
			$this->form_validation->set_rules('dokumentasi','Dokumentasi','required');
			$this->form_validation->set_rules('lokasi_koordinat','Lokasi Koordinat','required');
			$this->form_validation->set_rules('lokasi_distrik','Lokasi Distrik','required');
			$this->form_validation->set_rules('lokasi_kabkota','Lokasi Kabkota','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'infrastruktur' => $this->input->post('infrastruktur'),
					'tgl_laporan' => $this->input->post('tgl_laporan'),
					'nama_pelapor' => $this->input->post('nama_pelapor'),
					'no_ktp' => $this->input->post('no_ktp'),
					'foto_ktp' => $this->input->post('foto_ktp'),
					'lokasi_namajalan' => $this->input->post('lokasi_namajalan'),
					'lokasi_kabkota' => $this->input->post('lokasi_kabkota'),
					'lokasi_distrik' => $this->input->post('lokasi_distrik'),
					'lokasi_koordinat' => $this->input->post('lokasi_koordinat'),
					'dokumentasi' => $this->input->post('dokumentasi'),
					'alamat' => $this->input->post('alamat'),
					'pengaduan' => $this->input->post('pengaduan'),
                );

                $this->Laporan_model->update_laporan($id,$params);            
                redirect('laporan/index');
            }
            else
            {
                $data['_view'] = 'laporan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The laporan you are trying to edit does not exist.');
    } 

    /*
     * Deleting laporan
     */
    function remove($id)
    {
        $laporan = $this->Laporan_model->get_laporan($id);

        // check if the laporan exists before trying to delete it
        if(isset($laporan['id']))
        {
            $this->Laporan_model->delete_laporan($id);
            redirect('laporan/index');
        }
        else
            show_error('The laporan you are trying to delete does not exist.');
    }
    
}
